Liat kedmi pandas puzzles
anat-vainer/python_training pull request #1
Opened 2024-04-08 09:51 UTC by liat500

Solved all pandas puzzles.

2024-04-08 11:23 UTC, CarmelKatz1 requested changes
![image](https://github.com/anat-vainer/python_training/assets/166387683/b97537b1-dd21-450a-8c90-423a9cc3eb2a)
test

2024-04-08 11:24 UTC, CarmelKatz1 commented
test

2024-04-08 11:25 UTC, liat500 commented
> test

2024-04-08 11:35 UTC, CarmelKatz1 commented
![image](https://github.com/anat-vainer/python_training/assets/166387683/5c97c2b6-6899-4e91-a1d1-b0f34a41278f)
צריך שמספר הvisits יהיה גדול מ3, לא הage

2024-04-08 11:42 UTC, CarmelKatz1 commented
![image](https://github.com/anat-vainer/python_training/assets/166387683/5bb692c3-5b39-4188-98d8-642c752c1b24)
כתוב inclusive אז צריך שהגיל יהיה >= מ4 ו<= מ2

2024-04-11 11:05 UTC, leperv commented
![image](https://github.com/anat-vainer/python_training/assets/73588004/801a38fc-1cfb-4f76-a3c7-272333bf876f)
השם שבחרת לציין איתו את כמות השורות של הספרה השמאלית מבלבל, כי הוא גם השם של האינדקס.
כדאי שתחליפי אותו לשם שמציין את זה שיש ספירה

2024-04-11 11:20 UTC, leperv commented
![image](https://github.com/anat-vainer/python_training/assets/73588004/3a7f7a05-15cb-4715-abf5-8d75fa93002b)
השאלה מדברת על טבלה של 10X10 ואני רואה שעשית על טבלה של 7X7

2024-04-11 11:33 UTC, leperv commented
<img width="593" alt="image" src="https://github.com/anat-vainer/python_training/assets/73588004/4434ae1e-7a79-4231-92fb-51b3fa961e95">
בנוגע לתנאי שסימנתי.
בשאלה כתוב שאם לא נמצא עוד אפס, צריך להחזיר את המרחק מתחילת הרשימה.
עם הפתרון שלך כרגע, את מחזירה 1- במקום המרחק מתחילת הרשימה.
חוץ משני התאים הראשונים, כל שאר התאים עם הערכים הנכונים.
שימי לב שיש לך את איך התשובה צריכה להראות בסוף השאלה

2024-04-30 11:45 UTC, leperv approved these changes

2024-05-02 13:29 UTC, anat-vainer approved these changes, later dismissed

2024-05-02 13:31 UTC, leperv approved these changes

2024-05-02 13:41 UTC, anat-vainer approved these changes

2024-05-02 13:41 UTC, merged